import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/Components/Navbar";
import Footer from "@/Components/Footer";
import AosAnimtaion from "@/SharedComponents/AosAnimtaion";
import Spinner from "@/SharedComponents/Spinner";
import Progressbar from "@/SharedComponents/Progressbar";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className='font-outfit overflow-y-scroll snap-none'>
        <Spinner>
        <Navbar />
        <AosAnimtaion />
        <Progressbar />
        {children}
        <Footer />
        </Spinner>
      </body>
    </html>
  );
}
